### ISSUE TITLE
map_iso_gene already loaded

### ISSUE THREAD

**Issue by kvittingseerup** [SimoneTiberi/IsoBayes#10]
In line with Issue #7 could you also enable us to use a data.frame with already loaded gene association data for the `map_iso_gene` in the `inference()` function? Would mean that consequtive runs did not have to load the data every time :-)

**Comment by SimoneTiberi** [comment]
Right, good point; although loading TPMs is a very cheap step (in computational terms).
But I agree that it'd be convenient if data is already loaded in R.

I'll do this in January.

**Comment by kvittingseerup** [comment]
I was actually thinking about the `iso:gene` data file.

And it all adds up when you run it many times ;-)

**Comment by SimoneTiberi** [comment]
Oh, right, you wrote `map_iso_gene`!
Well, I think it's true for both cases; I'll allow both options (but I'll do it ~later).

Thanks for the suggestion Kristoffer.

**Comment by SimoneTiberi** [comment]
Hey Kris @kvittingseerup,
I've done it!
inference function can now load isoform-gene ids from a csv or a data.frame.
Sorry for the long time!
From version 1.2.5.

Simone
