### ISSUE TITLE
Use transformed intensities

### ISSUE THREAD

**Issue by kvittingseerup** [SimoneTiberi/IsoBayes#2]
When using the "Input user-provided data" approach described in the [vignette](https://github.com/SimoneTiberi/IsoBayes/blob/main/vignettes/IsoBayes.Rmd#L157), should the "intensities" be transformed and if so how?

**Comment by jbollon** [comment]
Hi @kvittingseerup ,
No, there is no need to transform the intensities.  In our code, we handle the intensities in the following way:
1) we normalize the intensities;
2) we multiply the normalized intensities by 10^5;
3) we round the normalized intensities.

https://github.com/SimoneTiberi/IsoBayes/blob/015826d14bbc2a4adbbd360b9ac5154969abf25f/R/load.R#L124

Cheers,
Jb

**Comment by kvittingseerup** [comment]
Thanks!

I'm a bit surprised there is no log transformation involved anywhere since the dynamic range of protein intensities (not counts) is so large ( [2.24e+05,3.73e+10] for the file I currently have open). Am I doing anything wrong? 😅

**Comment by jbollon** [comment]
Hi @kvittingseerup ,
see #5 

Cheers
