### ISSUE TITLE
Better error message when using map_iso_gene

### ISSUE THREAD

**Issue by kvittingseerup** [SimoneTiberi/IsoBayes#3]
I accidentally made a `map_iso_gene` file where some isoforms were not present and got this somewhat cryptic error message:

```
Error in aggregate.data.frame(t(results_MCMC$Y), by = list(results_MCMC$isoform_results$Gene),  : 
  arguments must have same length
```

Have a feeling I'll not be the last to make this mistake, so you might want to implement a check here :-)

Cheers
Kristoffer

**Comment by jbollon** [comment]
Hi @kvittingseerup ,

great suggestion!  It'll be without a doubt a common mistake. In the last version (IsoBayes_0.99.5) I added a warning message: basically we remove from the normalized results the isoforms not found in map_iso_gene.

Thanks a lot,
Jordy
