### ISSUE TITLE
Description of output

### ISSUE THREAD

**Issue by kvittingseerup** [SimoneTiberi/IsoBayes#4]
`IsoBayes::inference` output 3 different `data.frames`. Could you provide a description of what is in each column of them? 

I think I can guess but I'd rather know for sure :-)

**Comment by jbollon** [comment]
Hi @kvittingseerup ,
you can find the detailed description in the vignettes. Perhaps we can also include the description (or a brief summary) in the IsoBayes::inference documentation... We'll think about it. Anyway, in the IsoBayes::inference documentation (see the last package version (IsoBayes_0.99.5) just uploaded) we included a message suggesting to check out the vignettes for more information.

**Comment by kvittingseerup** [comment]
Thanks! Sorry I only looked in the documentation page 😅
