### ISSUE TITLE
Request for load_data option when data is already in R

### ISSUE THREAD

**Issue by kvittingseerup** [SimoneTiberi/IsoBayes#7]
A lot of us already have the data in R since we prefilter it (removing peptides flagged for contamination etc) and e.g. MaxQunat outputs one file with all sample intensities as columns. 

Would it be possible for you to provide a way to prepare the data object `inference()` needs when I already have the all data (as described in the [vignette](https://github.com/SimoneTiberi/IsoBayes/blob/f7cee5e893fe4d0ee76910528ea4987762f32bd0/vignettes/IsoBayes.Rmd#L157)) within R (so I don't need to write a file and then read it in again 🙂 ).

**Comment by SimoneTiberi** [comment]
Good point: noted it on our todo list!

**Comment by jbollon** [comment]
Now you can pass a data.frame to load_data()!

**Comment by SimoneTiberi** [comment]
Thanks Jordy.
In the near future, we'll consider loading MaxQunat outputs directly.

**Comment by kvittingseerup** [comment]
Thanks 😄
