### ISSUE TITLE
IsoBayes Data interface

### ISSUE THREAD

**Issue by lgatto** [SimoneTiberi/IsoBayes#9]
I'm following up from the [Bioconductor review issue](https://github.com/Bioconductor/Contributions/issues/3084) to discuss and plan the data interface to IsoBayes' main function. To summarise what was discussed in the Bioconductor issue:

- Use a well tested Bioconductor class as main data structure for the package, namely `SummarizedExperiment`. 
- To support other types of input, either write helper functions that will convert them into a `SummarizedExperiment` object, or delegate to `QFeatures`, that already support import arbitrary csv files.

**Comment by lgatto** [comment]
As a general function for csv files, there's [QFeatures::readSummarizedExperiment()](https://rformassspectrometry.github.io/QFeatures/reference/readQFeatures.html).

**Comment by SimoneTiberi** [comment]
Hi Laurent,
done it (and push to Bioc); version 1.0.1.

`load_data` only inputs a SE object.

To simplify usage, we also provide a `generate_SE` function to create the SE in the structure `load_data` wants, starting from the inputs of Percolator, Metamorpheus or a tsv file.

Alternatively, users can generate the SE as they wish -> the vignette was extended accordingly to explain how the SE should be structured.

I'll close the issue, but please let us know if you have comments about this.

Thanks again for your suggestions!
Simone and Jordy
